### PR TITLE
Cash register

### PR DESCRIPTION
**Pull request by shogof**
### Description

This pull request introduces a basic **cash register** application. It uses HTML, CSS, and JavaScript to create a simple tool for calculating totals for entered item prices.

### Features

- **HTML**: Basic structure for the cash register interface.
- **CSS**: Simple styling for a clear and functional design.
- **JavaScript**: Functions for adding item prices, calculating the total, and resetting the form.

### How to Test

1. Open `index.html` in a web browser.
2. Enter item prices and click "Purchase button" to see the final amount.
4. Enter another item prices to check.

### Notes

- **Future Improvements**: Possible features include tax calculation and advanced user interface options.
- **Technology Used**
`HTML`  `CSS`  `JavaScript`

### CODE REVIEW

**Comment by shogof** [comment]
**Hi @royajamal! 😊 I hope everything’s going well for you. 🌟 I just submitted a pull request for my project on GitHub and would really appreciate your review when you get a chance. Looking forward to your thoughts! 🙏 Thanks a bunch**

**Comment by royajamal** [comment]
@shogof 
Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

Highlights 🌞
🎉 Great Design Implemented
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validator project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Comment by shogof** [comment]
@ahzamir 
**Hello teacher 😊 I hope everything’s going well for you. 🌟 I would really appreciate your review when you get a chance. Looking forward to your thoughts! 🙏 Thanks you so much**

**Review by ahzamir — CHANGES_REQUESTED** [review]
@shogof 

- Well done your project functionality is perfect and also you implemented lots of requirements, still your project has one issue with the responsiveness please solve the problem and mention me here for a re-review on your project:
  - It has a little bit of scroll
  - [OPTIONAL] - Change the sizing of your menu cards to make them a little bit smaller on the mobile version it will make it more cool.
image

**Review by ahzamir — APPROVED** [review]
### Hi @shogof 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
